# <img src="https://img.icons8.com/bubbles/100/000000/3d-glasses.png" style="height:50px;display:inline"> EE 046746 - Technion - Computer Vision


## Homework 0 - Python & Basic Image Processing
---

### <a style='color:red'> Due Date: 06.04.2021 </a>

### <img src="https://img.icons8.com/bubbles/50/000000/checklist.png" style="height:50px;display:inline"> Agenda
---

* Getting to Know Python
    * NumPy
    * Matplotlib
    * Scikit-Learn
* Image Processing 101

#### Use as many cells as you need

### <img src="https://img.icons8.com/bubbles/50/000000/information.png" style="height:50px;display:inline"> Students Information
---
* Fill in

|Name     |Campus Email| ID  |
|---------|--------------------------------|----------|
|Daniel Teitelman| daniel.tei@campus.technion.ac.il| 207734088|
|Yair Nahum| nahum.yair@campus.technion.ac.il| 034462796|


### <img src="https://img.icons8.com/bubbles/50/000000/upload-to-cloud.png" style="height:50px;display:inline"> Submission Guidelines
---
* Submission only in **pairs**.
* **No handwritten submissions.** 
* What you have to submit:
    * You should submit this file only, with the name: `ee046746_hw0_id1_id2.ipynb`.
    * No other file-types (`.py`, `.docx`...) will be accepted.
* Submission on the course website (Moodle).

### <img src="https://img.icons8.com/clouds/96/000000/keyboard.png" style="height:50px;display:inline"> Keyboard Shortcuts
---
* Run current cell: **Ctrl + Enter**
* Run current cell and move to the next: **Shift + Enter**
* Show lines in a code cell: **Esc + L**
* View function documentation: **Shift + Tab** inside the parenthesis or `help(name_of_module)`
* New cell below: **Esc + B**
* Delete cell: **Esc + D, D** (two D's)

In [23]:
# imports for the tutorial
import numpy as np
import matplotlib.pyplot as plt
import cv2
%matplotlib inline

### <img src="https://img.icons8.com/dusk/64/000000/python.png" style="height:50px;display:inline"> Introduction to Python
---
In this part, we are going to cover some of the basics in Python (it is easy, don'y worry...).

All you have to do is run all the cells, and perform a really simple exercise at the end of each section.

## <img src="https://img.icons8.com/clouds/100/000000/calculator.png" style="height:50px;display:inline"> NumPy
---

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* A powerful N-dimensional array object

* Sophisticated (broadcasting) functions

* Tools for integrating C/C++ and Fortran code

* Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases



### Numpy Array
#### 1D List -> NumPy Array

In [24]:
vec = [1, 2, 3] # list
np_vec = np.array(vec) # array
print(type(np_vec)) # check the type
print(np_vec) # print the array

<class 'numpy.ndarray'>
[1 2 3]


#### 2D Matrix -> Numpy Array

In [25]:
mat = [[2, 6, 8], [3, 7, 0]] # 2d list
np_mat = np.array(mat) # 2d ndarray
print(np_mat) # print the matrix

[[2 6 8]
 [3 7 0]]


#### Zeros, Ones, Eye

In [26]:
# zeros, just like matlab
zero_arr = np.zeros((3,4))
print("zeros:")
print(zero_arr)
# ones, just like matlab
print("ones:")
one_arr = np.ones((3,4))
print(one_arr)
# identity matrix, just like matlab
print("eye:")
eye_arr = np.eye(3)
print(eye_arr)

zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random
#### Create Random Arrays and Numbers with NumPy

In [27]:
np.random.randn(5) # 5x1 array with numbers from N(0,1)

array([-0.07208584, -2.69222675,  0.76849868,  1.07878911,  0.57720445])

In [28]:
np.random.randn(3,4) # 3x4 matrix with numbers from N(0,1)

array([[-1.94199122,  0.44466411,  1.70190557, -1.32657621],
       [-0.75242785,  2.03415952,  1.77936467,  1.67867515],
       [-0.28460052, -0.05910696,  0.33450442, -0.64972063]])

In [29]:
np.random.randint(5, 15) # random integer between start (5) and end (15)

5

In [30]:
np.random.randint(5, 150, 5) # multiple (5) random numbers between specified range

array([ 51,  63,  59,  55, 142])

### Series of Numbers
#### arange, linspace

In [31]:
np.arange(3, 12) # 3, 4..., 11

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np.arange(3, 12, 2) # with a step of 2

array([ 3,  5,  7,  9, 11])

In [33]:
np.linspace(2, 5) # as in matlab default count is 50 -- third argument

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [34]:
np.linspace(2, 5, 10) # third argument specifies the count of numbers

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

### NumPy Operations

Very similar to MATLAB

In [35]:
# dimensions of arrays
print(np_vec.shape)
print(np_mat.shape)

(3,)
(2, 3)


In [36]:
# maximum and minimum
print("max: {}".format(np_mat.max()))
print("min: {}".format(np_mat.min()))

max: 8
min: 0


In [37]:
# reshape
print(np_mat)
print("reshape:")
print(np_mat.reshape(3,2)) # change dimensions -- only if the total number of values remains the same

[[2 6 8]
 [3 7 0]]
reshape:
[[2 6]
 [8 3]
 [7 0]]


In [38]:
np_mat.reshape(3, 4) # error since total number of elements changes

ValueError: cannot reshape array of size 6 into shape (3,4)

### Numpy Array Operations
#### Operations between arrays and scalars

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5])
print("a = ")
print(a)
print("a + 7 = ")
print(a + 7) # add 7 to each element
print("a + 2 = ")
print(a - 2)
print("a / 2 = ")
print(a / 2)
print("a * 3 = ")
print(a * 3)
print("sin(a) = ")
print(np.sin(a)) # sin() of each element, same dimensions
print("sum(a) = ")
print(np.sum(a)) # sum of all elements
print("mean(a) = ")
print(np.mean(a)) # mean of the array

In [ ]:
a1 = np.array([[1, 3], [4, 6]])
print("a1 = ")
print(a1)
b1 = np.array([[0, 2], [3, 1]])
print("b1 = ")
print(b1)

In [ ]:
print("a1 + b1 = ")
print(a1 + b1)
print("a1 * b1 = ")
print(a1 * b1) # element-wise multiplication
print("matrix multiplication: np.dot(a1, b1) = ")
print(np.dot(a1, b1)) # matrix multiplication
print("np.dot() is the same as using @: a1 @ b1 = ")
print(a1 @ b1) # matrix multiplication

In [ ]:
# element-wise comparison
print(a > 2) # compare each and every element

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 1

Create 2 random matrices of the following shapes:
* $a \in \mathcal{R}^{2 \times 3} $
* $b \in \mathcal{R}^{3 \times 2} $

And perform matrix multiplication.

In [ ]:
"""
Your Code Here
"""
a = np.random.randn(2,3)
b = np.random.randn(3,2)
a @ b

### Indexing, Slicing, Broadcasting

In [ ]:
d1 = np.arange(25)
print(d1)

In [ ]:
d2 = np.arange(25).reshape(5,5)
print(d2)

In [ ]:
# slicing
d1[4:12] # slicing -- d1[start : end+1]

In [ ]:
print("d1[4: ] = ")
print(d1[4: ])
print("d1[:13] = ")
print(d1[:13])

In [ ]:
print("d2[0,0] = ")
print(d2[0,0]) # d2[row, column]
print("d2[2,] = ")
print(d2[2,])
print("d2[:, 3]")
print(d2[:, 3])

In [ ]:
# broadcasting
print("d1[0:5] = ")
print(d1[0:5])
print("d1[0:5] = -10")
d1[0:5] = -10 # broadcasting -- Change specific elements of the array
print(d1[0:5])

## <img src="https://img.icons8.com/dusk/64/000000/area-chart.png" style="height:50px;display:inline"> Matplotlib
---

A 2D plotting library which produces publication quality figures.
 - Can be used in python scripts, the python and IPython shell, web application servers, and more …
 - Can be used to generate plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc.
 - For simple plotting, pyplot provides a MATLAB-like interface 
 - For power users, a full control via OO interface or via a set of functions

There are several Matplotlib add-on toolkits
 - Projection and mapping toolkits [basemap](http://matplotlib.org/basemap/) and [cartopy](http://scitools.org.uk/cartopy/).
 - Interactive plots in web browsers using [Bokeh](http://bokeh.pydata.org/en/latest/).
 - Higher level interface with updated visualizations [Seaborn](http://seaborn.pydata.org/index.html).

Matplotlib is available at [www.matplotlib.org](www.matplotlib.org)

## Line Plots

### Plot Against Indices

In [ ]:
x = np.arange(50) * 2 * np.pi / 50
y = np.sin(x)
fig = plt.figure(figsize=(8, 5)) # create a figure, just like in matlab
ax = fig.add_subplot(1, 1 ,1) # create a subplot of certain size
ax.plot(y, label="y = sin(x)")
ax.set_xlabel('index')
ax.set_ylabel("sin(x)")
ax.set_title("sin(x)")
ax.grid()
ax.legend()

### Multiple Lines

In [ ]:
x2 = np.arange(50) * 2 * np.pi / 25
y2 = np.sin(x2)
fig = plt.figure(figsize=(8, 5)) # create a figure, just like in matlab
ax = fig.add_subplot(1, 1 ,1) # create a subplot of certain size
ax.plot(y, label="y1 = sin(x1)")
ax.plot(y2, 'r-^', label="y2 = sin(x2)")
ax.set_xlabel('index')
ax.set_ylabel("sin(x)")
ax.set_title("sin(x)")
ax.grid()
ax.legend()

### Scatter Plots

In [ ]:
x = np.arange(50) * 2 * np.pi / 50
y = np.sin(x)
fig = plt.figure(figsize=(8, 5)) # create a figure, just like in matlab
ax = fig.add_subplot(1, 1 ,1) # create a subplot of certain size
ax.scatter(x, y, label="y = sin(x)")
ax.set_xlabel('index')
ax.set_ylabel("sin(x)")
ax.set_title("scatter sin(x)")
ax.grid()
ax.legend()

### Bar Plots

In [ ]:
fig = plt.figure(figsize=(10, 8)) # create a figure, just like in matlab
ax1 = fig.add_subplot(2, 1 ,1) # create a subplot of certain size
ax1.bar(x, y)
ax1.set_xlabel('x')
ax1.set_ylabel("y")
ax1.set_title("bar plot")
ax1.grid()

ax2 = fig.add_subplot(2, 1 ,2) # create a subplot of certain size
ax2.barh(x, y, height=x[1]-x[0])
ax2.set_xlabel('x')
ax2.set_ylabel("y")
ax2.set_title("barh plot")
ax2.grid()

plt.tight_layout()

### Histogram

In [ ]:
fig = plt.figure(figsize=(8, 5)) # create a figure, just like in matlab
ax = fig.add_subplot(1, 1 ,1) # create a subplot of certain size
ax.hist(np.random.randn(1000), 30) # 30 is the number of bins
ax.set_title("histogram")
ax.grid()

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 2

Create 1000 values using `linspace` and plot $sin(x) + cos(x)$ both as `plot` and `scatter` as 2 different subplots

In [ ]:
"""
Your Code Here
"""
x = np.linspace(0,2 * np.pi,1000)
y = np.sin(x) + np.cos(x)
plt.figure(figsize = (8,8))
plt.subplot(1,2,1)
plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Plot of sin(x) + cos(x)')
plt.grid()
plt.subplot(1,2,2)
plt.scatter(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Scatter plot of sin(x) + cos(x)')
plt.grid()

plt.tight_layout()

## <img src="https://img.icons8.com/cotton/64/000000/artificial-intelligence.png" style="height:50px;display:inline"> Scikit-Learn
---
Scikit-learn is an open source machine learning library for Python.  
 - **Simple and efficient** tools for data mining and data analysis
 - Good coverage of machine learning algorithms, processes, tools and techniques
   - Classification, Regression, Clustering, Dimensionality Reduction, Model selection, Preprocessing
 - **High standards** 
 - Well-suited for applications:
   - Used for **large datasets**
   - **Building blocks** for application-specific algorithms
 - Built on **NumPy, SciPy**
 - **Open source**, Commercially usable - BSD license, Community driven

Data Representation in Scikit-learn:
 - Most algorithms expect a two-dimensional array, of shape (n_samples,n_features).
 - The arrays can be either NumPy arrays, or in some cases scipy.sparse matrices.
   - The number of features must be fixed in advance.
   
Design principles
 - Minimize number of object interfaces
 - Build abstractions for recurrent use cases
 - Simplicity, Simplicity, Simplicity
 
Code samples:
> 
``from sklearn import svm
clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)``

Classification:
>``y_pred = model.predict(X_test)``

Filters, dimension reduction, latent variables:
>``X_new = model.transform(X_test)``

Incremental learning:
>``model.partial_fir(X_train, y_train)``

---

The [scikit-learn website](http://scikit-learn.org/stable/) has great tutorials for using their library  
---
The [preprocessing](http://scikit-learn.org/stable/modules/preprocessing.html#preprocessing) page has information that is very relevant for the second exercise.

A more interfactive tutorial introducing scikit-learn can be found [here](https://www.datacamp.com/community/tutorials/machine-learning-python#gs.Ae7Ua_Y).

### Example - The Digits Dataset
(Taken from https://scikit-learn.org/stable/tutorial/basic/tutorial.html)

#### Loading the Data
A dataset is a dictionary-like object that holds all the data and some metadata about the data. This data is stored in the `.data` member, which is a `n_samples, n_features` array. In the case of supervised problem, one or more response variables are stored in the `.target` member. More details on the different datasets can be found in the dedicated section.

In [ ]:
# import dataset
from sklearn import datasets
digits = datasets.load_digits()

For instance, in the case of the digits dataset, `digits.data` gives access to the features that can be used to classify the digits samples:

In [ ]:
print(digits.data)

and `digits.target` gives the ground truth for the digit dataset, that is the number corresponding to each digit image that we are trying to learn:

In [ ]:
print(digits.target)

Shape of the data arrays

The data is always a 2D array, shape `(n_samples, n_features)`, although the original data may have had a different shape. In the case of the digits, each original sample is an image of shape `(8, 8)` and can be accessed using: `digits.images`

In [ ]:
fig = plt.figure(figsize=(8, 5)) # create a figure, just like in matlab
ax = fig.add_subplot(1, 1 ,1) # create a subplot of certain size
ax.imshow(digits.images[0], cmap='gray')
ax.set_title("digits.image[0]")

#### Learning and Predicting

In the case of the digits dataset, the task is to predict, given an image, which digit it represents. We are given samples of each of the 10 possible classes (the digits zero through nine) on which we fit an estimator to be able to predict the classes to which unseen samples belong.

In scikit-learn, an estimator for classification is a Python object that implements the methods `fit(X, y)` and `predict(T)`.

In [ ]:
from sklearn.model_selection import train_test_split
# split to train and test sets
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)
# fit a Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
# train
clf.fit(X_train, y_train)
# predict
y_pred = clf.predict(X_test)
# cacluclate accuracy
print("prediction accuracy: {:.3f}%".format(np.mean(y_pred == y_test) * 100))

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 3

Build a Linear Support Vector Machine (SVM) classifier using `LinearSVC()` class from `sklearn` and check the accuracy.

In [ ]:
from sklearn.svm import LinearSVC

# split to train and test sets
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

"""
Your Code Here
"""

clf = LinearSVC()
# train
clf.fit(X_train, y_train)
# predict
y_pred = clf.predict(X_test)
# cacluclate accuracy
print("prediction accuracy: {:.3f}%".format(np.mean(y_pred == y_test) * 100))

### <img src="https://img.icons8.com/office/80/000000/edit-image.png" style="height:50px;display:inline"> Image Processing 101
---
In this part, we are going to cover some of the basics in OpenCV

Use the first tutorial if you are not yet comfortable with OpenCV.

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 4

Load the image `oy.jpg` and display it.

In [ ]:
"""
Your Code Here
"""
import os 
oy = cv2.imread("oy.jpg")
fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(cv2.cvtColor(oy, cv2.COLOR_BGR2RGB))
ax.set_title('oy')
ax.set_axis_off()

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 5

Convert the image to gray and apply adpative thresholdind using `cv2.adaptiveThreshold` with the following values:

* `adaptiveMethod=cv2.ADAPTIVE_THRESH_GAUSSIAN_C`
* `thresholdType=cv2.THRESH_BINARY`
* `blockSize=11`
* `C=2`

In [ ]:
"""
Your Code Here
"""
oy_gray = cv2.cvtColor(oy, cv2.COLOR_BGR2GRAY)
oy_gray_threshold = cv2.adaptiveThreshold(oy_gray,maxValue=255,adaptiveMethod=cv2.ADAPTIVE_THRESH_GAUSSIAN_C,thresholdType=cv2.THRESH_BINARY,blockSize=11,C=2)
oy_img_threshold = cv2.cvtColor(oy_gray_threshold, cv2.COLOR_GRAY2RGB)

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(oy_img_threshold)
ax.set_title('oy adaptive threshold')
ax.set_axis_off()

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 6

We are now going to cover some classic object detection and morphology concepts.

* Load the image `coins.jpg` and display it.
* Convert it to gray and apply Gaussian Blur to smooth it (use a kernel size of 5). Display the resulting image.
* Apply binary threshold using `cv2.threshold(, , , type=cv2.THRESH_BINARY)`. The recommended threshold is around 130, pick the one you are most satisfied with. Invert the colors such that the coins are white and the background is black, use `cv2.bitwise_not()`. Display the result.
* We now want to clean the image to create a better mask. We will use the "Closing" morphological transformation. As you recall, the "Closing" operation is applying Dilation followed by Erosion. It is applied by `closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)` (<a href="https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html">Read more</a>). For the `kernel`, use a matrix of ones with size 15x15. Display the result.

In [ ]:
"""
Your Code Here
"""
# use as many cells as you need

coins = cv2.imread("coins.jpg")

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(cv2.cvtColor(coins, cv2.COLOR_BGR2RGB))
ax.set_title('Coins')
ax.set_axis_off()

coins_gray = cv2.cvtColor(coins, cv2.COLOR_BGR2GRAY)
coins_gray_gaussianblur = cv2.GaussianBlur(coins_gray, (5,5),cv2.BORDER_DEFAULT)
coins_img_gaussianblur = cv2.cvtColor(coins_gray_gaussianblur, cv2.COLOR_GRAY2RGB)

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(coins_img_gaussianblur)
ax.set_title('Coins gray gaussian blur')
ax.set_axis_off()

_, coins_gray_gaussianblur_binarythreshold = cv2.threshold(coins_gray_gaussianblur, thresh = 160,maxval = 255, type=cv2.THRESH_BINARY)
coins_gray_gaussianblur_binarythreshold_flip = cv2.bitwise_not(coins_gray_gaussianblur_binarythreshold, mask = None)
coins_img_gaussianblur_binarythreshold_flip = cv2.cvtColor(coins_gray_gaussianblur_binarythreshold_flip, cv2.COLOR_GRAY2RGB)
fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(coins_img_gaussianblur_binarythreshold_flip)
ax.set_title('Coins gray gaussian blur binary threshold flipped')
ax.set_axis_off()

kernel = np.ones(15)
coins_closed = cv2.morphologyEx(coins_gray_gaussianblur_binarythreshold_flip, cv2.MORPH_CLOSE, kernel)
coins_closed_img = cv2.cvtColor(coins_closed, cv2.COLOR_GRAY2RGB)
fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(coins_closed_img)
ax.set_title('Coins after closing operation')
ax.set_axis_off()

### <img src="https://img.icons8.com/color/96/000000/deadlift.png" style="height:50px;display:inline"> Exercise 7

We are now going to detect the number of coins in the image using contours. Contours can be explained simply as a curve joining all the continuous points (along the boundary), having same color or intensity. The contours are a useful tool for shape analysis and object detection and recognition. For better accuracy, it is better to use binary images. So before finding contours, apply threshold or canny edge detection.

* Using the binary image of the the coins from the previous exercise, use `cv2.findContours(..., mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)` to find the contours.
* Filter contours that are too small to define a coin, use `cv2.contourArea()` to get the area of the contour. The minimum value should be in 50-70.
* Make a copy of the original image with `np.copy(coins)`, draw the filtered contours on the copied image using `cv2.drawContours(.., ..., contourIdx=-1, color=(255, 0, 0))`. Finally, display the image with the contours (`cv2.drawContours` draws the contours but doesn't display them, use `imshow` to display the image).
* Print the number of coins in the image (it is the number of detercted contours).

In [ ]:
"""
Your Code Here
"""
coins_closed[coins_closed < 10] = 0
coins_closed[coins_closed >= 10] = 255

contours,hierarchy = cv2.findContours(coins_closed, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
area = cv2.contourArea(cnt)
print('Area: ' + str(area))
print('Min area: ' + str(np.min(contours[1])))
coins2 = np.copy(coins)
drawingCon = cv2.drawContours(coins2, contours, contourIdx=-1, color=(255, 0, 0), thickness=3)

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(1,1,1)
ax.imshow(cv2.cvtColor(drawingCon, cv2.COLOR_BGR2RGB))
ax.set_title('Detect Coins')
ax.set_axis_off()
print(f'Detected all {contours.shape[0]} coins')


## <img src="https://img.icons8.com/dusk/64/000000/prize.png" style="height:50px;display:inline"> Credits
* Icons from <a href="https://icons8.com/">Icon8.com</a> - https://icons8.com
* Datasets from <a href="https://www.kaggle.com/">Kaggle</a> - https://www.kaggle.com/